### PR TITLE
apm v3

### PR DESCRIPTION
**Pull request by vmarchaud**

### CODE REVIEW

**Comment by Unitech** [comment]
Is there a clean, worded changelog somewhere about the improvements made + new metrics by default + the one that can be activated? I can't see in either CHANGELOG or README

**Comment by vmarchaud** [comment]
No because its not finished yet, most of the change are in this commit tho https://github.com/keymetrics/pm2-io-apm/pull/214/commits/df5c6e282f85ca8ce7914a9b816734553dd8fd48

**Comment by Unitech** [comment]
ok looking forward to have this synthetic explanation of new changes incoming once you feel the new version of pmx ready to be published, thanks

**Comment by vmarchaud** [comment]
Breaking changes:

- Removed `io.scopedAction`
- Removed `io.notify` in favor of `io.notifyError`
- Removed support for `gc-stats` module
- Removed heap snapshot when using the inspector and node 11
- Removed Heap profiling support when using the profiler addon
- Removed deep-metrics support
- Removed Entrypoint class
- Removed the possibility to set the value of a metrics via a function, now user should set the value when they want to update a metrics.
- Removed `io.transpose`
- When creating multiple metrics at the same time, metrics will now be returned in an array to allow simpler destruction
- Changed the `io.init` options to be easier to understand and manage in the code
- Allowed to use the inspector-based in node 8 if running in production (we assume that no other debugger is running in production)

Notable changes:
- Introduced the tracing system without PM2 (still using the old tracing agent)
- Added support for `@pm2/node-runtime/stats` to collect GC stats, libuv metrics and kernel metrics
- Added error middleware for Koa and fixed the one for Express
- When destroying a pmx instance, actually remove everything listener that we have on all kind of modules so we don't leak something when instancing multiples times
- Added P95 metrics about http latency and event loop ones.
- Added metrics about Heap usage, Heap limit and Heap current.
- Node 11 now support custom actions
- Added a LOT, LOT of logging about what's happening, just use `DEBUG=axm:*` to toggle it

Improvements;
- Remove easily replaceable dependency
- Use typescript to run the tests (before test were compiled before ran)
- Use Idle notifier of Nodejs to better vizualise iddle time in CPU profiling
- Type completion when using any methods from `@pm2/io`
- Metrics that are created but never used will not be sended to backend

Notes:
- scopedAction implementation is still there, just not exposed in the API
- Entrypoint was "removed" because i didn't understand the implementation while refactoring, but could be trivially re-implemented

**Comment by Unitech** [comment]
event loop latency + event loop latency p95 should be floored at the second decimal

**Comment by vmarchaud** [comment]
@Unitech RSS is the `memory` metric in case of using the standalone app, so i don't think it's useful to re-add it as a separate metric

**Pull request merged**
