### PR TITLE
Allow inspector only on node 10

### PR DESCRIPTION
**Pull request by wallet77**

### CODE REVIEW

**Comment by wallet77** [comment]
Problem is node v8 doesn't support multi sessions for inspector.
So if user use --inspect or inspector directly into code, application will crash.

**Comment by vmarchaud** [comment]
Understood, there should be a env variable injected in the process to tell if pm2 is linked to the SaaS

**Comment by Unitech** [comment]
we have process.env.km_link, we're gonna merge this PR to make people using node 8 able to start their application with --inspect and also be able to profile CPU/MEM via pm2 plus

**Comment by vmarchaud** [comment]
We should at least provide an option to force the native profiling in node 8

**Comment by Unitech** [comment]
yes could be possible via an environment variable for example

**Pull request merged**
